name: "IndexNow"
on:
  push:
    branches:
      - main
  schedule:
    # scheduled in UTC.
    - cron:  '0 0,12 * * *'
    
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup IndexNow # Generate files dynamically to prevent them from being leaked in public repositories.
        run: echo ${{ secrets.INDEXNOW_KEY }} > ${{ secrets.INDEXNOW_KEY }}.txt
        
      - name: submit-to-bing
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "https://eupho.me/sitemap.xml"  # change it
          since: 1
          # minite, hour, day, week, month, year
          since-unit: "month"
          key: ${{ secrets.INDEXNOW_KEY }}